const DBSchemaConstants = {
  ORIG_STATE_MASTERS: "ORIG_STATE_MASTERS",
  ORIG_CITY_MASTERS: "ORIG_CITY_MASTERS",
  ORIG_ZONAL_MASTER: "ORIG_ZONAL_MASTER",
  ORIG_BRANCH_MASTER: "ORIG_BRANCH_MASTER",
  ORIG_STATIC_DATA_MASTERS: "ORIG_STATIC_DATA_MASTERS",
  ZONE_ID: "ZONE_ID",
  BRANCH_ID: "BRANCH_ID",
};
export default DBSchemaConstants;
