const DBSchemaConstants = {
  ORIG_STATE_MASTERS: "ORIG_STATE_MASTERS",
  ORIG_CITY_MASTERS: "ORIG_CITY_MASTERS",
  ORIG_ZONAL_MASTER: "ORIG_ZONAL_MASTER",
  ORIG_BRANCH_MASTER: "ORIG_BRANCH_MASTER",
  ORIG_STATIC_DATA_MASTERS: "ORIG_STATIC_DATA_MASTERS",
  PRODUCT_MAIN_CATEGORY: "PRODUCT_MAIN_CATEGORY",
  PRODUCT_SUB_CATEGORY: "PRODUCT_SUB_CATEGORY",
  ZONE_ID: "ZONE_ID",
  BRANCH_ID: "BRANCH_ID",
  LOV_ID: "LOV_ID",
  STATE_ID: "STATE_ID",
  CITY_ID: "CITY_ID",
  PRODUCT_MAIN_ID: "PRODUCT_MAIN_ID",
  PRODUCT_SUB_ID: "PRODUCT_SUB_ID",
};
export default DBSchemaConstants;
