import { Button, KeyboardAvoidingView, StyleSheet, View } from "react-native";
import React from "react";
import { Formik, FormikValues } from "formik";
import { Styledtextinput, StyledDropdown } from "@/components/formcontrols";
import { ScrollView } from "react-native-gesture-handler";
import { SourcingFormInitialData } from "@/apptypes";
import { SourcingFormValidationSchema } from "@/apptypes/AppValidationSchemas";

const validationSchema = SourcingFormValidationSchema;
const SourcingPage = () => {
  return (
    <KeyboardAvoidingView>
      <ScrollView>
        <View className="py-5 px-2">
          <Formik
            initialValues={SourcingFormInitialData}
            onSubmit={(values) => alert(JSON.stringify(values))}
            validationSchema={validationSchema}
          >
            {(formikProps: FormikValues) => (
              <>
                <StyledDropdown
                  placeholder="Select Business"
                  title="Business Description"
                  mandatory={true}
                  formikProps={formikProps}
                  formikkey="businessdescription"
                />

                <StyledDropdown
                  placeholder="--Select--"
                  title="Sourcing Channel"
                  mandatory={true}
                  formikProps={formikProps}
                  formikkey="sourcingchannel"
                />

                <Styledtextinput
                  label="Sourcing ID"
                  formikProps={formikProps}
                  formikkey="sourcingid"
                  placeholder="Enter User ID"
                  mandatory={true}
                />

                {/* password text field */}
                <Styledtextinput
                  label="Sourcing Name"
                  formikProps={formikProps}
                  formikkey="sourcingname"
                  placeholder="Enter User Name"
                  mandatory={true}
                />

                <StyledDropdown
                  placeholder="--Select--"
                  title="Preffered Branch"
                  mandatory={true}
                  formikProps={formikProps}
                  formikkey="preferredbranch"
                />

                <Styledtextinput
                  label="Branch Code"
                  formikProps={formikProps}
                  formikkey="branchcode"
                  placeholder="Enter Branch Code"
                  mandatory={true}
                />

                <Styledtextinput
                  label="Lead Generated By"
                  formikProps={formikProps}
                  formikkey="leadby"
                  placeholder=""
                  mandatory={true}
                />

                <Styledtextinput
                  label="Lead ID"
                  formikProps={formikProps}
                  formikkey="leadid"
                  placeholder=""
                  mandatory={true}
                />

                <Styledtextinput
                  label="Customer Name"
                  formikProps={formikProps}
                  formikkey="customername"
                  placeholder="Enter Customer Name"
                  mandatory={true}
                />
                <Styledtextinput
                  label="Date Of Birth"
                  formikProps={formikProps}
                  formikkey="dob"
                  placeholder="Enter Date Of Birth"
                  mandatory={true}
                />

                <Styledtextinput
                  label="Mobile Number"
                  formikProps={formikProps}
                  formikkey="mobileno"
                  placeholder="Enter Mobile Number"
                  mandatory={true}
                />
                <StyledDropdown
                  placeholder="--Select--"
                  title="Product Interested"
                  mandatory={true}
                  formikProps={formikProps}
                  formikkey="productinterested"
                />
                {/*  */}
                <Button title="Submit" onPress={formikProps.handleSubmit} />
              </>
            )}
          </Formik>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

export default SourcingPage;
